version: '3'
services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: MyDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '4306:3306'
    volumes:
      - ./.docker/mysql:/var/lib/mysql
  php:
    build:
      context: ./.docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
      image: nginx:stable-alpine
      ports:
        - '8000:80'
      volumes:
        - ./:/var/www/symfony_docker
        - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - database